#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "commands.h"
#include "history.h"
#include "ls.h"
#include "discover.h"
#include "pinfo.h"
#include "process.h"
#include <assert.h>
#include <sys/wait.h>
#include "jobs.h"
#include "fgbg.h"
#include <signal.h>
#include "sig.h"
#include "signals.h"